spring:
  application:
    name: ms-payment
  
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:payment_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api/v1
  tomcat:
    threads:
      max: 1000 
      min-spare: 50
